name: Build Doc

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js, npm
        uses: mbruno46/websmith.js@main
        with:
          config: './examples/config.json'
          path: './doc'
